services:
  db:
    container_name: products-db
    image: mysql:9.0.1
    volumes:
      - products-db-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MySuperSecretPassword
      MYSQL_DATABASE: products
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
  
  migrate:
    container_name: products-db-migration 
    depends_on:
      db:
        condition: service_healthy
    environment:
      - "ConnectionStrings__ProductsDb=server=products-db;database=products;user=root;password=MySuperSecretPassword"
    build:
      context: ./src/
      dockerfile: /Demo.Products.API/Dockerfile
      target: migrate
    command: ["dotnet", "ef", "database", "update"]

  api:
    container_name: products-api
    depends_on:
      migrate:
        condition: service_completed_successfully
    build:
      context: ./src/
      dockerfile: /Demo.Products.API/Dockerfile
      target: final
    ports:
      - 8080:8080
  
volumes:
  products-db-mysql-data:
